"""empty message

Revision ID: 2012a939838f
Revises: 4e51357c4991
Create Date: 2019-05-22 09:54:40.140363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2012a939838f'
down_revision = '4e51357c4991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
