"""empty message

Revision ID: 6a1c3714eab1
Revises: 2012a939838f
Create Date: 2019-05-23 10:43:10.414797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a1c3714eab1'
down_revision = '2012a939838f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtopics', sa.Column('display_order', sa.Integer(), nullable=True))
    op.drop_column('subtopics', 'order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtopics', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('subtopics', 'display_order')
    # ### end Alembic commands ###
