"""empty message

Revision ID: a7c3d06907e0
Revises: 9235c5ab8f20
Create Date: 2019-05-21 14:27:55.730327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c3d06907e0'
down_revision = '9235c5ab8f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtopics', sa.Column('description', sa.String(), nullable=True))
    op.add_column('topics', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'description')
    op.drop_column('subtopics', 'description')
    # ### end Alembic commands ###
