"""empty message

Revision ID: c82be923dbec
Revises: 2012a939838f
Create Date: 2019-05-22 17:47:36.104784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82be923dbec'
down_revision = '2012a939838f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'url')
    # ### end Alembic commands ###
